# Generated by Django 5.1.4 on 2025-12-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_testsubmission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, help_text='Rich HTML content for the lesson page', null=True),
        ),
    ]
