# Generated by Django 5.1.4 on 2025-12-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lesson_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
        migrations.AddField(
            model_name='lesson',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
